/* Generated By:JavaCC: Do not edit this line. Word2VecTokenizerConstants.java */
package tokenizer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Word2VecTokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HTML = 1;
  /** RegularExpression Id. */
  int HTML_COMMENT = 2;
  /** RegularExpression Id. */
  int WHITESPACE = 3;
  /** RegularExpression Id. */
  int JS = 4;
  /** RegularExpression Id. */
  int CODE_BLOCK = 5;
  /** RegularExpression Id. */
  int BLOCK_COMMENT = 6;
  /** RegularExpression Id. */
  int LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int PUNCTUATION = 8;
  /** RegularExpression Id. */
  int PRE_TAG = 9;
  /** RegularExpression Id. */
  int NUMBER = 10;
  /** RegularExpression Id. */
  int HTML_ENTITIES = 11;
  /** RegularExpression Id. */
  int EMAIL = 12;
  /** RegularExpression Id. */
  int PHONE = 13;
  /** RegularExpression Id. */
  int NOT_WORD = 14;
  /** RegularExpression Id. */
  int WORD = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<HTML>",
    "<HTML_COMMENT>",
    "<WHITESPACE>",
    "<JS>",
    "<CODE_BLOCK>",
    "<BLOCK_COMMENT>",
    "<LINE_COMMENT>",
    "<PUNCTUATION>",
    "<PRE_TAG>",
    "<NUMBER>",
    "<HTML_ENTITIES>",
    "<EMAIL>",
    "<PHONE>",
    "<NOT_WORD>",
    "<WORD>",
  };

}
